<?xml version="1.0"?>
<robot xmlns:xacro="https://wiki.ros.org/xacro">

    <!--    XACRO VARIABLES-->
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_thick" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="lidar_radius" value="0.1" />
    <xacro:property name="lidar_length" value="0.05" />

    <!--    XACRO MACROS-->
    <xacro:macro name="wheel_link" params="prefix" >
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            </visual>
        </link>
    </xacro:macro>


    <!--    links-->
    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_thick}" />
            </geometry>
            <origin xyz="0 0 ${base_thick/2}" rpy="0 0 0" />
            <material name="green" />
        </visual>
    </link>

    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="white" />
        </visual>
    </link>

    <xacro:wheel_link prefix="right" />

<!--    <xacro:wheel_link prefix="left" />-->
    <link name="left_wheel_link">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/meshes/left_tire.dae" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
    </link>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
    </link>

    <!--    joints-->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar" />
        <origin xyz="0 0 ${base_thick+lidar_length/2}" rpy="0 0 0" />
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="-${base_length/4} -${(base_width + wheel_length)/2}  0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="-${base_length/4} ${(base_width + wheel_length)/2}  0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel" />
        <origin xyz="${base_length/3.0} 0 -${wheel_radius/2.0}" rpy="0 0 0" />
    </joint>
</robot>
