<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="https://wiki.ros.org/xacro">

    <!--    XACRO VARIABLES-->
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_thick" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="lidar_radius" value="0.1" />
    <xacro:property name="lidar_length" value="0.05" />

    <!--    materials-->
    <material name="gray">
        <color rgba="0.7 0.7 0.7 1" />
    </material>

    <material name="green">
        <color rgba="0 0.6 0 0.6" />
    </material>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <!--    links-->

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_thick}" />
            </geometry>
            <origin xyz="0 0 ${base_thick/2}" rpy="0 0 0" />
            <material name="green" />
        </visual>
    </link>


    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="white" />
        </visual>
    </link>


    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        </visual>
    </link>


    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        </visual>
    </link>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
    </link>

<!--    joints-->

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>


    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar" />
        <origin xyz="0 0 ${base_thick+lidar_length/2}" rpy="0 0 0" />
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="-${base_length/4} -${(base_width + wheel_length)/2}  0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>


    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin xyz="-${base_length/4} ${(base_width + wheel_length)/2}  0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>


    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel" />
        <origin xyz="${base_length/3.0} 0 -${wheel_radius/2.0}" rpy="0 0 0" />
    </joint>


</robot>